version: "3.9"
services:
  admin:
    build: .\admin
    ports:
      - "5001:5001"
  frontend:
    build: .\frontend
    ports:
      - "3000:3000"
  server:
    build: .\server
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

